### PR TITLE
Fixes "Select Interpreter"

### PR DESCRIPTION
**Pull request by sleighsoft**
https://github.com/microsoft/vscode-python/issues/7140

### CODE REVIEW

**Review by davidleininger — COMMENTED** [review]
Would you rather see this be a color? Something to help it stand out?

**Review by davidleininger — APPROVED** [review]
After looking into it, I see that this is specifically for high contrast themes. I'll also be getting rid of `contrastBorder` as both are set to invisible. Thanks for pointing this out.

**Comment by sleighsoft** [comment]
Glad to help. Thanks for brining cobaltnext to vscode!

**Comment by davidleininger** [comment]
My pleasure. Please let me know if you find anything else.

**Pull request merged**
